docs: add: v1 do readme + imagens diagramas DDD
diorgeneseugenio/fiap-tech-challenge-soat pull request #17
Opened 2023-07-02 20:38 UTC by JulianaAmoasei

Retirados do readme:
* escopo original do projeto
* descrição das features

Adicionados:
* tutorial de instalação
* instruções para execução e acesso aos endpoints
* descrição da estrutura de diretórios

Por favor revisem o texto (e os números de RM) e vejam se falta alguma coisa.

Obs: essa versão do readme depende da aprovação do PR #9 para termos a URL do swagger.

2023-07-02 22:23 UTC, EltonARodrigues commented on README.md
> +Os endpoints disponíveis, suas descrições e dados necessários para requisição podem ser consultados e testados em http://localhost/3000/api/api-docs.
O link correto pro swagger: 

http://localhost/3000/api-docs

2023-07-02 22:25 UTC, EltonARodrigues commented
Apenas uma correção e de qualquer forma a gente revisa e adiciona mais coisas antes de entregar

2023-07-02 22:27 UTC, EltonARodrigues requested changes
Apenas uma correção e de qualquer forma a gente revisa e adiciona mais coisas antes de entregar

2023-07-03 01:14 UTC, JulianaAmoasei commented on README.md
> +Os endpoints disponíveis, suas descrições e dados necessários para requisição podem ser consultados e testados em http://localhost/3000/api/api-docs.
vou corrigir :)
mas podemos deixar o PR aberto para pegar mais comentários

2023-07-03 14:41 UTC, gabrielmendessilva approved these changes

2023-07-05 17:49 UTC, diorgeneseugenio approved these changes

2023-07-05 20:24 UTC, EltonARodrigues approved these changes

2023-07-06 01:35 UTC, closed without merging