feat: possibilidade de criar usuarios anonimos
diorgeneseugenio/fiap-tech-challenge-soat pull request #18
Opened 2023-07-04 00:41 UTC by EltonARodrigues

Mudei a API de usuário para criar sem utilizar e-mail e/ou CPF.

Caso a pessoa não quera se identificar ela pode colocar qualquer coisa no campo nome apenas para definir como deve ser chamada, caso ela não coloque um nome no banco ficara como Anonimo.

Acredito que com isso finaliza a parte de usuários da primeira fase

2023-07-04 02:24 UTC, JulianaAmoasei requested changes

2023-07-04 02:24 UTC, JulianaAmoasei commented on src/core/applications/services/usuarioService.ts
> +        if (!usuario.cpf && !usuario.email) {
qualquer novo usuário que tenha **ou** nome + email **ou** npme + cpf está caindo direto no `filtraUsuario` e lançando o erro `usuário já existe` da linha 29

acho que não ficou claro pra mim se ou vai fazer o cadastro apenas por nome ou somente com todos os dados

2023-07-04 11:01 UTC, EltonARodrigues commented on src/core/applications/services/usuarioService.ts
> +        if (!usuario.cpf && !usuario.email) {
A ideia é que se vc passar o no body ou o email e/ou o cpf ele verifique se o usuario já existe no banco, mas se usar um sem nada ou apenas o nome ai ele apenas gera um novo

2023-07-04 11:03 UTC, EltonARodrigues commented on src/core/applications/services/usuarioService.ts
> +        if (!usuario.cpf && !usuario.email) {
Eu deixei pra usar ou o email, ou o cpf, ou os dois, mas talvez seja bom deixa o cpf obrigatório e o email opcional

2023-07-05 01:38 UTC, EltonARodrigues commented
Tava achando estranho isso não estava funcionando até perceber que não tinha feito o push....

2023-07-05 17:23 UTC, JulianaAmoasei approved these changes

2023-07-05 17:23 UTC, merged